### ISSUE TITLE
OpenCMS context menu doesn't show up or is empty

### ISSUE THREAD

**Issue by interone-ms** [mediaworx/opencms-intellijplugin#11]
In IntelliJ 2022.1.3/macOS 12.3, the menu under Tools->OpenCMS is empty (when hovering on it, no options show), and it is completely absent from both the Tab and Project Files context menus.

It may be possible that this bug is related to #10 as this bug may cause the initialization to error out and so the menus are not initialized.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/25393749/177812029-31fa2b8c-81a2-4cbe-9956-d786d58b8d5c.png">

<img width="393" alt="image" src="https://user-images.githubusercontent.com/25393749/177811620-8e8ae60e-c2e9-487c-a57b-03e7b0a44c7c.png">

**Comment by kaiwidmann** [comment]
The plugin version 1.12.3 containing a hotfix for this issue is now waitung for approval from JetBrains
