### ISSUE TITLE
Feature request: Option to migrate modules with root outside /system/modules

### ISSUE THREAD

**Issue by bjornbak** [mediaworx/opencms-intellijplugin#5]
Inspired by the Git Checkin functionality presented on OpenCms Days 2015 I would like to be able to export modules containing content a site of /sites/XXX on our production opencms and sync it into my development copy.

But a module containing a site does not contain full path but only the paths relative to the site root /sites/XXX.

Your plugin is hardcoded to be relative to / (at least in the ideconnector) with 
                cmsObject.getRequestContext().setSiteRoot("/");
in line 313 of src/main/java/com/mediaworx/opencms/ideconnector/OpenCmsIDEConnector.java

I have not been able to find the same in the CMIS sync yet.

**Comment by kaiwidmann** [comment]
This is definitely something worth considering. We don't run into the problem, 'cause all our modules are relative to root, but other OpenCms developers work differently. So this should be integrated in a future version. But as usual there's no time frame.

**Comment by kaiwidmann** [comment]
Hi bjornbak, 

it's been a while, I've been busy working on projects. But now I'll start working on that feature, a new release should be out within the next few weeks.

Cheers

Kai

**Comment by kaiwidmann** [comment]
It's integrated in the 1.9 release
