### ISSUE TITLE
Version 1.9 is not working with latest IDEA

### ISSUE THREAD

**Issue by haukeh** [mediaworx/opencms-intellijplugin#7]
Hi, sadly the newest plugin version seems to be incompatible with the latest IDEA version: 

```
IntelliJ IDEA 2016.1.3
Build #IU-145.1617, built on June 3, 2016
```

The preferences menu ~~and the context menu~~ for the plugin simply disappeared when I updated the plugin. My opencms.xml in the .idea/ folder seems to have the correct values. If I find the time, I will try to investigate this further myself. Of course I will place a pull-request if I have any luck in finding the reasons.

**Edit: Context menu is still working. My bad. Preferences menu still not available...** 

Best Regards,
Hauke

**Comment by kaiwidmann** [comment]
Hello Hauke,

thank you for reporting this. I don’t have the most recent IntelliJ installed right now, but I will download the most recent community edition and see what happens.

Cheers

Kai

**Comment by kaiwidmann** [comment]
I now have IntelliJ 2016.1 CE installed and can confirm that there's a problem with the settings. The whole "Other Settings" node is gone in the configuration dialog. There has been a change in IntelliJ's configuration architecture ages ago (configuration no longer is a "component" but an "extension"), but the old way worked up until recently. 
Now I have to change the plugin to work the "extension" way, I already have the configuration dialog back, but the whole way of persisting configuration data has to be rebuilt as well. 
Anyway, an update is on the way, I think it will be there by tomorrow.

**Comment by haukeh** [comment]
Wow, that's great news, Kai! Thanks a lot for tackling the problem right away 👍

**Comment by kaiwidmann** [comment]
The new version 1.9.1 was uploaded to IntelliJ's plugin repository and should be available shortly. 
The configuration dialog can now be found unter Settings > Tools > OpenCms Plugin.
