### ISSUE TITLE
IntelliJ crash on Opencms sync during debugging

### ISSUE THREAD

**Issue by KennethWussmann** [mediaworx/opencms-intellijplugin#8]
Hey,

when you sync local changes to the running OpenCms instance while you are using the debugger, IntelliJ will crash.

**Steps to reproduce**
1. Open a OpenCms Module IntellIJ project with enabled `opencms-intellijplugin`
2. Start the OpenCms (in Tomcat for example) within IntelliJ with debugger
3. Set an IntelliJ debugger breakpoint
4. Do something that triggers this breakpoint
5. Sync files using your `opencms-intellijplugin` while this breakpoint is triggered and the execution is on hold 

**Actual behavior**
IntelliJ will no longer respond (GUI freezes and process needs to be killed).

**Expected behavior**
Some sort of message/alert that syncing doesn't work while debugging.

**Setup**
**IntelliJ IDEA**: 2018.1.4 (also noticed on 2017.x)
**macOS**: High Sierra 10.13.2 (also noticed on Windows 7 & 10)
**opencms-intellijplugin**: v1.9.3 (also noticed on lower versions)

Thanks for your help,
Kenneth Wußmann

**Comment by kaiwidmann** [comment]
Hey Kenneth,

this is a known issue. Actually I don’t know if there’s much that can be done about this. Since the JVM you’re trying to sync to is halted, the sync hangs. Maybe there is a way to check if debugging is active and a breakpoint is keeping the program paused. Or if a timeout for the sync process might help. But in the meantime my advice is: don’t sync and debug at the same time ;)
You can avoid the IntelliJ crash by force stopping the OpenCms JVM (at least on mac). Then IntelliJ will unfreeze and react normally again.

Cheers

Kai

**Comment by KennethWussmann** [comment]
Hey Kai,

thanks for your response. 

It is possible to get the running debugging sessions using:
```Java
XDebugSession[] debugSessions = XDebuggerManager.getInstance(plugin.getProject()).getDebugSessions();
```
`debugSessions` will contain all running debug sessions and a `XDebugSession` has an [`isPaused()` getter](https://github.com/joewalnes/idea-community/blob/master/platform/xdebugger-api/src/com/intellij/xdebugger/AbstractDebuggerSession.java#L23) which should represent that this session is currently halting the JVM.
But I'm not 100% sure that this is a bullet proof way to test this.

**Comment by kaiwidmann** [comment]
Hey Kenneth, 

thanks a lot for the code snippet, that looks promising. I'll try to integrate that into the sync actions some time soon. 

Cheers 

Kai

**Comment by KennethWussmann** [comment]
Hey Kai, 

awesome, thank you. For sure it's not a big issue, but It's sometimes a little annoying when I accidentally press my sync shortcut.

Cheers,
Kenneth

**Comment by kaiwidmann** [comment]
Hey Kenneth, 

I think it's more than a little annoying, it happens to me from time to time as well and I always think that I should find a way to avoid that deadlock. So I'm eager to try your proposed solution.

Cheers,

Kai

**Comment by kaiwidmann** [comment]
Hey Kenneth, 

I uploaded a new version containing the suggested fix to the Jetbrains plugin repository. It should be available shortly. You got a honorable mention in the [Version History](/mediaworx/opencms-intellijplugin/wiki/Version-History).

Best wishes and thanks again

Kai

**Comment by KennethWussmann** [comment]
Hey Kai,

that was blazing fast, thanks a lot.
